# Generated by Django 3.0.3 on 2020-09-14 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0003_auto_20200914_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='parent_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campgrounds.Zone'),
        ),
    ]
