# Generated by Django 3.0.3 on 2020-09-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0008_auto_20200918_0503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
