# Generated by Django 3.0.3 on 2020-09-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campground',
            new_name='Campgroundz',
        ),
        migrations.RenameModel(
            old_name='Zone',
            new_name='Zonez',
        ),
    ]
